CREATE TABLE "MEMBER" (
    "USER_CODE" NUMBER      NOT NULL,
    "USER_NAME" VARCHAR2(30)        NOT NULL,
    "USER_PWD"  VARCHAR2(100)       NOT NULL,
    "USER_EMAIL"    VARCHAR2(100)       NOT NULL,
    "USER_PHONE"    VARCHAR2(20)        NOT NULL,
    "USER_BIRTH"    DATE        NOT NULL,
    "USER_ID"   VARCHAR2(30)        NOT NULL,
    "USER_TYPE" VARCHAR2(30) DEFAULT 'User'        NOT NULL,
    "STATUS"    CHAR(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_TYPE" IS 'Admin/User/Host';

COMMENT ON COLUMN "MEMBER"."STATUS" IS 'Y or N';

CREATE TABLE "RESERV" (
    "V_CODE"    NUMBER      NOT NULL,
    "CHECK_IN"  DATE        NOT NULL,
    "CHECK_OUT" DATE        NOT NULL,
    "PERSONNEL" VARCHAR2(100)       NOT NULL,
    "ROOMS_CODE"    NUMBER      NOT NULL,
    "USER_CODE" NUMBER      NOT NULL,
    "STATUS"    VARCHAR(1)  DEFAULT 'Y' NOT NULL,
    "RESERV_PRICE"  NUMBER      NOT NULL
);

COMMENT ON COLUMN "RESERV"."PERSONNEL" IS 'Min. 1';

COMMENT ON COLUMN "RESERV"."STATUS" IS 'Y or N';

CREATE TABLE "REVIEW" (
    "R_CODE"    NUMBER      NOT NULL,
    "R_CONTENT" NVARCHAR2(200)      NOT NULL,
    "R_UPDATE"  DATE        NOT NULL,
    "R_MODFIY"  DATE        NOT NULL,
    "USER_CODE" NUMBER      NOT NULL,
    "ROOMS_CODE"    NUMBER      NOT NULL,
    "STATUS"    CHAR(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN "REVIEW"."STATUS" IS 'Y or N';

CREATE TABLE "PAYMENT" (
    "P_CODE"    NUMBER      NOT NULL,
    "P_STATUS"  VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    "V_CODE"    NUMBER      NOT NULL,
    "P_DATE"    DATE        NOT NULL,
    "IN_DATE"   DATE        NOT NULL,
    "OUT_DATE"  DATE        NOT NULL,
    "P_PRICE"   NUMBER      NOT NULL,
    "P_PERSONNEL"   VARCHAR2(100)       NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."P_STATUS" IS 'Y or N';

CREATE TABLE "MSG" (
    "MESSAGE_CODE"  NUMBER      NOT NULL,
    "MESSAGE_TITLE" VARCHAR2(20)        NOT NULL,
    "SENDTIME"  DATE        NOT NULL,
    "READTIME"  DATE        NOT NULL,
    "MSGTEXT"   VARCHAR2(300)       NULL,
    "SEND_ID"   VARCHAR2(30)        NOT NULL,
    "RECEIVE_ID"    VARCHAR2(30)        NOT NULL,
    "STATUS"    CHAR(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN "MSG"."STATUS" IS 'Y or N';

CREATE TABLE "SOOKSOIMG" (
    "IMAGE_NUMBER"  NUMBER      NOT NULL,
    "ORIGIN_NAME"   VARCHAR2(100)       NOT NULL,
    "CHANGE_NAME"   VARCHAR2(100)       NOT NULL,
    "IMG_LEVEL" NUMBER      NULL,
    "IMG_PATH"  VARCHAR2(300)       NOT NULL,
    "ROOMS_CODE"    NUMBER      NOT NULL,
    "STATUS"    VARCHAR2(20)    DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN "SOOKSOIMG"."IMG_LEVEL" IS '썸네일 or 일반사진';

COMMENT ON COLUMN "SOOKSOIMG"."STATUS" IS 'Y or N';

CREATE TABLE "ROOMS" (
    "ROOMS_CODE"    NUMBER      NOT NULL,
    "ROOMS_HOST"    VARCHAR2(300)       NOT NULL,
    "ROOMS_TYPE"    VARCHAR2(50)        NULL,
    "ROOMS_ADDR"    VARCHAR2(200)       NULL,
    "ROOMS_PRICE"   VARCHAR2(100)       NULL,
    "ROOMS_PERSONNEL"   VARCHAR2(100)        NULL,
    "ROOMS_ROOMCNT" VARCHAR2(100)       NULL,
    "ROOMS_TOILETCNT"   VARCHAR2(100)       NULL,
    "AMENITY"   VARCHAR2(300)       NULL,
    "ROOMS_DESC"    VARCHAR2(500)       NULL,
    "ROOMS_REGDATE" DATE        NULL,
    "STATUS"    VARCHAR2(50)    DEFAULT 'Y' NULL,
    "USER_CODE" NUMBER      NOT NULL,
    "ROOM_NAME" VARCHAR2(300)       NULL
);

COMMENT ON COLUMN "ROOMS"."ROOMS_PRICE" IS '원';

COMMENT ON COLUMN "ROOMS"."ROOMS_PERSONNEL" IS 'Min. 1';

COMMENT ON COLUMN "ROOMS"."ROOMS_ROOMCNT" IS 'Min. 1';

COMMENT ON COLUMN "ROOMS"."ROOMS_TOILETCNT" IS 'Min. 0';

COMMENT ON COLUMN "ROOMS"."STATUS" IS 'Y or N';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
    "USER_CODE"
);

ALTER TABLE "RESERV" ADD CONSTRAINT "PK_RESERV" PRIMARY KEY (
    "V_CODE"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
    "R_CODE"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
    "P_CODE"
);

ALTER TABLE "MSG" ADD CONSTRAINT "PK_MSG" PRIMARY KEY (
    "MESSAGE_CODE"
);

ALTER TABLE "SOOKSOIMG" ADD CONSTRAINT "PK_SOOKSOIMG" PRIMARY KEY (
    "IMAGE_NUMBER"
);

ALTER TABLE "ROOMS" ADD CONSTRAINT "PK_ROOMS" PRIMARY KEY (
    "ROOMS_CODE"
);

CREATE SEQUENCE SEQ_UID
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_RNO
START WITH 1
INCREMENT BY 1
MAXVALUE 300
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_INO
START WITH 1
INCREMENT BY 1
MAXVALUE 500
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;

CREATE OR REPLACE VIEW MLIST
AS
SELECT ROWNUM RNUM, M.*
FROM (SELECT MESSAGE_CODE, MESSAGE_TITLE, SENDTIME, READTIME, MSGTEXT, SEND_ID, RECEIVE_ID, MSG.STATUS
      FROM MSG
           JOIN MEMBER ON(USER_ID = RECEIVE_ID)
      WHERE MSG.STATUS = 'Y'
      ORDER BY SENDTIME DESC) M;

CREATE OR REPLACE VIEW RLIST
AS
SELECT ROWNUM RNUM, DESCROOMS.*
FROM(SELECT ROOMS_CODE, ROOMS_HOST, ROOMS_ADDR, ROOMS_PRICE, ROOMS_PERSONNEL, ROOMS_ROOMCNT,
            ROOMS_TOILETCNT, AMENITY, ROOMS_DESC, ROOMS_REGDATE, R.STATUS, USER_CODE
     FROM ROOMS R
        JOIN MEMBER USING(USER_CODE)
     WHERE R.STATUS = 'Y'
     ORDER BY ROOMS_CODE DESC) DESCROOMS;

CREATE SEQUENCE SEQ_PCD
START WITH 1
INCREMENT BY 1
MAXVALUE 500
MINVALUE 1
CYCLE
NOCACHE;

CREATE SEQUENCE SEQ_RVC
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;