-- RESERV테이블의 PERSONNEL 타입 변경 : VARCHAR2(100)
ALTER TABLE RESERV MODIFY PERSONNEL VARCHAR2(100);
   
-- RSERV테이블의 V_STATUS 삭제
ALTER TABLE RESERV DROP COLUMN V_STATUS;
   
-- RESERV테이블의 ROOM_NAME 삭제 
ALTER TABLE RESERV DROP COLUMN ROOM_NAME;

-- ROOMS테이블에 ROOM_NAME 생성
ALTER TABLE ROOMS ADD ROOM_NAME VARCHAR2(300);

-- RESERV테이블에 예약 가격 추가
ALTER TABLE RESERV ADD RESERV_PRICE NUMBER;

-- PAYMENT에 P_METHOD삭제 : 결제 시스템을 I'MPORT를 이용하게 되었기때문에 결제 방식은 받아올수 없어서 삭제하였습니다.
ALTER TABLE PAYMENT DROP COLUMN P_METHOD;

-- RESERV테이블의 STATUS 타입 수정 (CHAR -> VARCHAR2(1) )
ALTER TABLE RESERV MODIFY STATUS VARCHAR2(1);

-- PAYMENT테이블의 P_STATUS 타입 수정 (CHAR -> VARCHAR2(1) )
ALTER TABLE PAYMENT MODIFY P_STATUS VARCHAR2(1);


-- [ RESERV 테이블 SQL]
  CREATE TABLE "ODONATA"."RESERV" 
   (	"V_CODE" NUMBER NOT NULL ENABLE, 
	"CHECK_IN" DATE NOT NULL ENABLE, 
	"CHECK_OUT" DATE NOT NULL ENABLE, 
	"PERSONNEL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ROOMS_CODE" NUMBER NOT NULL ENABLE, 
	"USER_CODE" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"RESERV_PRICE" NUMBER, 
	 CONSTRAINT "PK_RESERV" PRIMARY KEY ("V_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- RESERV 시퀸스 : SEQ_RVC
-- MESSAGE_CODE 시퀀스 생성
CREATE SEQUENCE SEQ_RVC
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;

-- RESERV테이블의 STATUS에 DEFAULT값 설정
ALTER TABLE RESERV MODIFY STATUS DEFAULT 'Y';
  
  -- [PAYMENT 테이블 SQL]
    CREATE TABLE "ODONATA"."PAYMENT" 
   (	"P_CODE" NUMBER NOT NULL ENABLE, 
	"P_STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"P_TOTAL" NUMBER NOT NULL ENABLE, 
	"V_CODE" NUMBER NOT NULL ENABLE, 
	"P_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("P_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  -- PAYMENT 시퀸스 : SEQ_PCD
  CREATE SEQUENCE  "ODONATA"."SEQ_PCD"  MINVALUE 1 MAXVALUE 500 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- [추가] PAYMENT테이블에 P_TOTAL삭제 : RESERV에 RESERV_PRICE가 있기때문에 중복되므로 삭제
ALTER TABLE PAYMENT DROP COLUMN P_TOTAL;

-- [11/27 추가] PAYMENT테이블에 CHECKIN, CHECKOUT, PRICE, PRICE, PERSONNEL 추가
ALTER TABLE PAYMENT ADD IN_DATE DATE;
ALTER TABLE PAYMENT ADD OUT_DATE DATE;
ALTER TABLE PAYMENT ADD P_PRICE NUMBER;
ALTER TABLE PAYMENT ADD P_PERSONNEL VARCHAR2(100);


