
-- RESERV테이블의 PERSONNEL 타입 변경 : VARCHAR2(100)
ALTER TABLE RESERV MODIFY PERSONNEL VARCHAR2(100);
   
-- RSERV테이블의 V_STATUS 삭제
ALTER TABLE RESERV DROP COLUMN V_STATUS;
   
-- RESERV테이블의 ROOM_NAME 삭제 
ALTER TABLE RESERV DROP COLUMN ROOM_NAME;

-- ROOMS테이블에 ROOM_NAME 생성
ALTER TABLE ROOMS ADD ROOM_NAME VARCHAR2(300);

COMMIT;